[package]
name = "sql-processor-api"
description = "Axum HTTP API and static web server for SQL Processor"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
axum.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio.workspace = true
tower.workspace = true
tower-http.workspace = true
utoipa.workspace = true
utoipa-axum.workspace = true
sql-processor-core = { path = "../sql-processor-core" }
sql-processor-validation = { path = "../sql-processor-validation" }
