/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/process": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["process"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Config: {
            enabled: boolean;
            host?: string;
            password?: string;
            /** Format: int32 */
            port?: number;
            profileName?: string;
            service?: string;
            /** Format: int64 */
            timeoutSeconds?: number;
            username?: string;
        };
        HealthResponse: {
            status: string;
        };
        Issue: {
            code?: string | null;
            line: number;
            message: string;
            snippet?: string | null;
            statementType: string;
            status: string;
            unitIndex: number;
        };
        ProcessRequest: {
            schema?: string;
            sql: string;
            validationConfig?: null | components["schemas"]["Config"];
        };
        ProcessResponse: {
            error?: string | null;
            messages: string[];
            processedSql?: string | null;
            validation?: null | components["schemas"]["Result"];
        };
        Result: {
            targets: components["schemas"]["Target"][];
        };
        Target: {
            issues: components["schemas"]["Issue"][];
            status: string;
            summary: string[];
            target: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service health */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    process: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProcessRequest"];
            };
        };
        responses: {
            /** @description Processed SQL */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProcessResponse"];
                };
            };
            /** @description Invalid request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProcessResponse"];
                };
            };
            /** @description Processing failure */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProcessResponse"];
                };
            };
        };
    };
}
